WITH MAX_SCORE AS
(
    SELECT EMP_NO, SUM(SCORE) AS SCORE_SUM
    FROM HR_GRADE
    GROUP BY EMP_NO
    ORDER BY SCORE_SUM DESC
    LIMIT 1
)

SELECT MAX_SCORE.SCORE_SUM AS SCORE, EMP.EMP_NO, EMP.EMP_NAME, EMP.POSITION, EMP.EMAIL
FROM HR_EMPLOYEES EMP
JOIN MAX_SCORE ON EMP.EMP_NO = MAX_SCORE.EMP_NO
